    clear
    close all
    clc
    load('../Figure3a-0.2-Run3.mat','x0','T','gbig','safe_set','target_set','P','mean_x','xtarget','ono_opt_mean_X','onopwl_opt_mean_X','pwa_opt_mean_X','blackmore_opt_mean_X','N','slice_at_vx_vy');
    plot_markersize = 20;
    plot_fontSize = 20;
    figure(1);
    
    subplot(2,2,1);
    hold on
    h1 = plot(safe_set.slice([3,4], slice_at_vx_vy), 'color', 'y','alpha',0.5);
    h2 = plot(target_set.slice([3,4], slice_at_vx_vy), 'color', 'g','alpha',0.5);
    h3 = scatter(x0(1),x0(2),10*plot_markersize,'bo','filled');
    h4 = plot(onopwl_opt_mean_X(1:4:end),...
                onopwl_opt_mean_X(2:4:end),...
                'md','MarkerSize',plot_markersize);
    h5 = plot(ono_opt_mean_X(1:4:end),...
                ono_opt_mean_X(2:4:end),...
                'b^','MarkerSize',plot_markersize);
    h6 = plot(pwa_opt_mean_X(1:4:end),...
                pwa_opt_mean_X(2:4:end),...
                'r*','MarkerSize',plot_markersize);
    h7 = plot(blackmore_opt_mean_X(1:4:end,1),...
                blackmore_opt_mean_X(2:4:end,1),...
                'ks','MarkerSize',plot_markersize);

    xlabel('Position ($z_1$)')
    ylabel('Position ($z_2$)')
    set(gca,'FontSize',plot_fontSize)
    leg=legend([h1 h2 h3 h4 h5 h6 h7],{'Safe Set',...
        'Target Set','Initial Position',...
        'Piecewise affine approach - QP',...
        'Iterative risk allocation (IRA)',...
        'Piecewise affine approach - MIQP',...
        sprintf('Blackmore11 PC Method, %i Particles',N)},...
        'FontSize',plot_fontSize);
    set(leg,'Position', [0.4871 0.3621 0.2665 0.2522]);    
    box on;
    axis([-1 0.2 -1 0.05])
    set(gca,'FontSize',plot_fontSize)
    grid on
    
    load('../Figure3b-0.6.mat','x0','T','gbig','safe_set','target_set','P','mean_x','xtarget','ono_opt_mean_X','onopwl_opt_mean_X','pwa_opt_mean_X','blackmore_opt_mean_X','N','slice_at_vx_vy');
    subplot(2,2,3);
    hold on
    h1 = plot(safe_set.slice([3,4], slice_at_vx_vy), 'color', 'y','alpha',0.5);
    h2 = plot(target_set.slice([3,4], slice_at_vx_vy), 'color', 'g','alpha',0.5);
    h3 = scatter(x0(1),x0(2),10*plot_markersize,'bo','filled');
    h4 = plot(onopwl_opt_mean_X(1:4:end),...
                onopwl_opt_mean_X(2:4:end),...
                'md','MarkerSize',plot_markersize);
    h5 = plot(ono_opt_mean_X(1:4:end),...
                ono_opt_mean_X(2:4:end),...
                'b^','MarkerSize',plot_markersize);
    h6 = plot(pwa_opt_mean_X(1:4:end),...
                pwa_opt_mean_X(2:4:end),...
                'r*','MarkerSize',plot_markersize);
    h7 = plot(blackmore_opt_mean_X(1:4:end,1),...
                blackmore_opt_mean_X(2:4:end,1),...
                'ks','MarkerSize',plot_markersize);

    xlabel('Position ($z_1$)')
    ylabel('Position ($z_2$)')
    set(gca,'FontSize',plot_fontSize)
    axis([-1.15 0.2 -1.15 0.05])
    xtick_vec = get(gca,'XTick');
    set(gca,'XTick',[-1.15 -1:0.2:0.2]);    
    ytick_vec = get(gca,'YTick');
    set(gca,'YTick',[-1.15 -1:0.2:0.2]);    
    box on;
    set(gca,'FontSize',plot_fontSize)
    grid on

